export const POPULAR_GOOGLE_FONTS = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Source Sans 3",
  "Nunito",
  "Raleway",
  "Work Sans",
  "DM Sans",
  "Plus Jakarta Sans",
  "Space Grotesk",
  "IBM Plex Sans",
  "IBM Plex Mono",
  "JetBrains Mono",
  "Fira Code",
  "Playfair Display",
  "Merriweather",
  "Libre Baskerville",
  "Oswald",
  "Archivo",
  "Manrope",
  "Outfit",
  "Sora",
  "Geist",
] as const;
