import type { SiteType } from "./schema";

export interface SiteTypeOption {
  id: SiteType;
  label: string;
  description: string;
}

export const SITE_TYPE_OPTIONS: SiteTypeOption[] = [
  { id: "marketing", label: "Marketing", description: "Hero, features, and conversion CTAs." },
  { id: "landing-page", label: "Landing page", description: "One message and one primary action." },
  { id: "docs", label: "Docs", description: "Readable content and technical guidance." },
  { id: "dashboard", label: "Dashboard", description: "Dense product and data interfaces." },
  { id: "e-commerce", label: "E-commerce", description: "Products, pricing, and purchase flows." },
  { id: "portfolio", label: "Portfolio", description: "Work samples and visual storytelling." },
  { id: "saas-app", label: "SaaS app", description: "In-app chrome, side nav, and dense forms." },
  { id: "blog", label: "Blog", description: "Long-form reading and article hierarchy." },
  { id: "auth", label: "Auth", description: "Focused sign-in and onboarding flows." },
  { id: "admin", label: "Admin", description: "Operational tables, filters, and status UI." },
  { id: "mobile-app", label: "Mobile app", description: "Touch-first layouts and simplified nav." },
  { id: "marketplace", label: "Marketplace", description: "Listings, sellers, and discovery grids." },
  { id: "social", label: "Social", description: "Feeds, profiles, and engagement actions." },
  { id: "education", label: "Education", description: "Courses, lessons, and progress tracking." },
  { id: "booking", label: "Booking", description: "Schedules, availability, and reservations." },
  { id: "news", label: "News", description: "Headlines, sections, and article scanning." },
  { id: "community", label: "Community", description: "Discussions, groups, and member hubs." },
  { id: "agency", label: "Agency", description: "Services, case studies, and contact CTAs." },
  { id: "fintech", label: "Fintech", description: "Balances, transfers, and trust-heavy money UI." },
  { id: "healthcare", label: "Healthcare", description: "Appointments, records, and calm clinical clarity." },
  { id: "real-estate", label: "Real estate", description: "Listings, filters, and property detail pages." },
  { id: "food-delivery", label: "Food delivery", description: "Menus, carts, and order tracking." },
  { id: "travel", label: "Travel", description: "Search, itineraries, and destination cards." },
  { id: "music", label: "Music", description: "Playlists, player chrome, and album art." },
  { id: "podcast", label: "Podcast", description: "Episode lists, show notes, and listen CTAs." },
  { id: "crypto", label: "Crypto", description: "Wallets, charts, and on-chain status." },
  { id: "nonprofit", label: "Nonprofit", description: "Causes, impact stats, and donate flows." },
  { id: "event", label: "Event", description: "Schedules, speakers, and ticket CTAs." },
  { id: "hr-portal", label: "HR portal", description: "Time off, people directory, and policies." },
  { id: "legal", label: "Legal", description: "Practices, matters, and formal document UI." },
];

export function siteTypeLabel(siteType: SiteType): string {
  return SITE_TYPE_OPTIONS.find((o) => o.id === siteType)?.label ?? siteType.replace(/-/g, " ");
}

export const SITE_TYPE_GUIDANCE: Record<SiteType, string> = {
  marketing: "Structure pages around a hero band, feature cards, and a single primary CTA per viewport.",
  docs: "Favor readable body columns, sidebar navigation, and code-friendly monospace accents.",
  dashboard: "Prioritize data density, surface ladders, and compact spacing in table-heavy views.",
  "e-commerce": "Use consistent product cards, pricing tiers, and category badges across catalog pages.",
  portfolio: "Lead with oversized display type and generous whitespace; let work samples dominate.",
  "landing-page": "Keep navigation minimal and funnel attention to one headline and one conversion action.",
  "saas-app": "Design in-app chrome first - side nav, dense forms, and quiet surfaces that don't compete with content.",
  blog: "Optimize for reading: comfortable measure, strong heading hierarchy, and restrained UI chrome.",
  auth: "Keep the experience focused - centered forms, calm contrast, and one clear next step.",
  admin: "Default to dense operational UI - tables, filters, status badges, and compact controls.",
  "mobile-app": "Prioritize touch targets, simplified navigation, and content that works in a narrow viewport.",
  marketplace: "Make listings scannable - consistent cards, filters, and trust signals across sellers.",
  social: "Design for feed scanning - avatars, posts, and clear engagement actions.",
  education: "Guide learners through modules - progress, lessons, and calm instructional hierarchy.",
  booking: "Make availability obvious - calendars, time slots, and a clear confirmation path.",
  news: "Support fast scanning - section labels, headline hierarchy, and tight article cards.",
  community: "Highlight membership - threads, groups, and participation affordances.",
  agency: "Lead with credibility - services, case studies, and a strong contact CTA.",
  fintech: "Make money states unmistakable - balances, status, and irreversible actions need calm clarity.",
  healthcare: "Reduce anxiety - clear next steps, readable forms, and restrained decorative color.",
  "real-estate": "Lead with imagery and filters - price, beds, and location must stay scannable.",
  "food-delivery": "Optimize for hunger-speed decisions - menu cards, modifiers, and sticky cart CTAs.",
  travel: "Support exploration then commitment - search, dates, and itinerary confirmation.",
  music: "Keep playback chrome persistent - cover art, queue, and controls should feel tactile.",
  podcast: "Episode lists need duration, date, and play affordances without clutter.",
  crypto: "Numbers and risk states dominate - charts, wallet status, and confirmations must be precise.",
  nonprofit: "Lead with impact - stories, metrics, and a frictionless donate path.",
  event: "Schedule, speakers, and tickets should stay synchronized across the page.",
  "hr-portal": "People ops UI favors calm tables, policy clarity, and status badges.",
  legal: "Formal hierarchy - practice areas, matters, and document actions with restrained chrome.",
};

export const SITE_TYPE_DOS: Record<SiteType, string> = {
  marketing: "Lead with a hero band and a single primary CTA per viewport.",
  docs: "Prioritize readable body type and clear heading hierarchy for long-form content.",
  dashboard: "Default to compact spacing and a surface ladder in data-dense views.",
  "e-commerce": "Make product cards and pricing tiers visually consistent across the catalog.",
  portfolio: "Let large display type and generous whitespace carry the narrative.",
  "landing-page": "Keep the page focused - one message, one primary action, minimal nav.",
  "saas-app": "Keep chrome quiet - dense forms, clear side nav, and one primary action per panel.",
  blog: "Optimize for long-form reading: comfortable body size, clear headings, and calm chrome.",
  auth: "Minimize distraction - focused forms, calm contrast, and a single conversion path.",
  admin: "Favor dense tables, filters, and status badges over decorative marketing sections.",
  "mobile-app": "Design for touch: large tap targets, bottom-friendly actions, and simplified nav.",
  marketplace: "Keep listing cards consistent - image, title, price, and trust cues in the same order.",
  social: "Reserve primary color for engagement actions, not decorative chrome.",
  education: "Show progress clearly and keep lesson content wider than supporting chrome.",
  booking: "Make selected dates and times unmistakable before confirmation.",
  news: "Use strong headline hierarchy and keep metadata quieter than the story.",
  community: "Make membership and participation states obvious in lists and threads.",
  agency: "Lead with proof - case studies and outcomes before secondary service detail.",
  fintech: "Never bury irreversible money actions - confirmations need extra visual weight.",
  healthcare: "Prefer calm surfaces and clear form labels over decorative marketing chrome.",
  "real-estate": "Keep price and key facts visible on every listing card.",
  "food-delivery": "Keep the cart CTA sticky and modifiers easy to scan.",
  travel: "Make dates and travelers editable without leaving the search context.",
  music: "Playback controls should remain reachable while browsing.",
  podcast: "Show duration and publish date on every episode row.",
  crypto: "Use monospace for addresses and amounts; confirm destructive wallet actions twice.",
  nonprofit: "Put donation CTA above the fold and pair it with concrete impact metrics.",
  event: "Keep ticket status and schedule timezone explicit.",
  "hr-portal": "Status badges and policy links should be denser than marketing copy.",
  legal: "Use restrained color and strong typographic hierarchy for matters and documents.",
};
